namespace client
{
    using System;

    public enum NetManagerStatus
    {
        NETMANAGER_STATUS_NULL,
        NETMANAGER_STATUS_CONNECTING_GATE,
        NETMANAGER_STATUS_CONNECTED_GATE,
        NETMANAGER_STATUS_CONNECTING_SERVER,
        NETMANAGER_STATUS_CONNECTED_SERVER
    }
}

