namespace client
{
    using System;

    public enum ServerMsg
    {
        SERVER_CMSG_ACCOUNTINFO = 7,
        SERVER_CMSG_ADDTASK = 13,
        SERVER_CMSG_AUTH = 3,
        SERVER_CMSG_CHECKACCOUNT = 0x1b,
        SERVER_CMSG_COMPLETETASK = 0x19,
        SERVER_CMSG_CRPTKEY = 5,
        SERVER_CMSG_EDITACCOUNT = 0x1d,
        SERVER_CMSG_GETLOGININFO = 11,
        SERVER_CMSG_GETTASK = 15,
        SERVER_CMSG_MODIFYTASK = 0x11,
        SERVER_CMSG_MYTASK = 9,
        SERVER_CMSG_PING = 1,
        SERVER_CMSG_REMOVETASK = 0x17,
        SERVER_CMSG_RESUMETASK = 0x15,
        SERVER_CMSG_STOPTASK = 0x13,
        SERVER_MSG_LOGICBEGIN = 11,
        SERVER_MSG_NULL_ACTION = 0,
        SERVER_MSG_TYPES_NUM = 0x1f,
        SERVER_SMSG_ACCOUNTINFO = 8,
        SERVER_SMSG_ADDTASK = 14,
        SERVER_SMSG_AUTH = 4,
        SERVER_SMSG_CHECKACCOUNT = 0x1c,
        SERVER_SMSG_COMPLETETASK = 0x1a,
        SERVER_SMSG_CRPTKEY = 6,
        SERVER_SMSG_EDITACCOUNT = 30,
        SERVER_SMSG_GETLOGININFO = 12,
        SERVER_SMSG_GETTASK = 0x10,
        SERVER_SMSG_MODIFYTASK = 0x12,
        SERVER_SMSG_MYTASK = 10,
        SERVER_SMSG_PONG = 2,
        SERVER_SMSG_REMOVETASK = 0x18,
        SERVER_SMSG_RESUMETASK = 0x16,
        SERVER_SMSG_STOPTASK = 20
    }
}

